CREATE PLUGGABLE DATABASE mastergram_pdb
    ADMIN USER mastergram_pdb_admin IDENTIFIED BY 12345
    ROLES = (DBA)
    FILE_NAME_CONVERT = ('C:\app\valen\product\21c\oradata\XE\pdbseed', 'C:\app\valen\product\21c\oradata\XE\mastergram_pdb');
    
ALTER SESSION SET CONTAINER = "CDB$ROOT";
    
ALTER PLUGGABLE DATABASE mastergram_pdb OPEN;

ALTER SESSION SET CONTAINER = "mastergram_pdb";
GRANT EXECUTE ON UTL_FILE TO mastergram_app;
select * from dba_users;
--mastergram_pdb_admin
CREATE TABLESPACE mastergram_tablespace 
DATAFILE 'mastergram_tablespace.dbf' SIZE 200M;

CREATE USER mastergram_app IDENTIFIED BY 12345
DEFAULT TABLESPACE mastergram_tablespace QUOTA UNLIMITED ON mastergram_tablespace
ACCOUNT UNLOCK;

GRANT DBA to mastergram_app;

----ADMIN
CREATE PROFILE ADMIN_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 10
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

CREATE USER ADMIN IDENTIFIED BY 12345 PROFILE ADMIN_PROFILE
DEFAULT TABLESPACE mastergram_tablespace QUOTA UNLIMITED ON mastergram_tablespace
ACCOUNT UNLOCK;

GRANT DBA to ADMIN;

CREATE PROFILE USERS_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 20
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 3
    PASSWORD_REUSE_TIME 10
    CONNECT_TIME 180
    IDLE_TIME 60;

CREATE USER MASTER IDENTIFIED BY 12345 PROFILE USERS_PROFILE
DEFAULT TABLESPACE mastergram_tablespace
ACCOUNT UNLOCK;

GRANT CREATE SESSION TO MASTER;


CREATE USER CLIENT IDENTIFIED BY 12345 PROFILE USERS_PROFILE
DEFAULT TABLESPACE mastergram_tablespace
ACCOUNT UNLOCK;

GRANT CREATE SESSION TO CLIENT;
