CREATE TABLE Master_info (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(255),
    business_address VARCHAR2(255)
) TABLESPACE mastergram_tablespace;

CREATE TABLE Credential (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL
) TABLESPACE mastergram_tablespace;


CREATE TABLE Users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255) NOT NULL,
    first_name VARCHAR2(255),
    second_name VARCHAR2(255),
    city VARCHAR2(255),
    email VARCHAR2(255) UNIQUE,
    tel VARCHAR2(20),
    role VARCHAR2(50),
    profile_image BLOB,
    credential_id NUMBER,
    master_info_id NUMBER,
    CONSTRAINT fk_credential FOREIGN KEY (credential_id) REFERENCES Credential(id),
    CONSTRAINT fk_masterInfo FOREIGN KEY (master_info_id) REFERENCES Master_info(id)
) TABLESPACE mastergram_tablespace;

CREATE TABLE Post (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_image BLOB,
    description VARCHAR2(255),
    master_info_id NUMBER,
    CONSTRAINT fk_post_masterinfo FOREIGN KEY (master_info_id) REFERENCES Master_info(id)
) TABLESPACE mastergram_tablespace;


CREATE TABLE Booking (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id NUMBER,
    master_id NUMBER,
    service VARCHAR2(255),
    booking_date DATE,
    time TIMESTAMP,
    booked NUMBER(1) DEFAULT 0 CHECK (booked IN (0, 1)),
    master_comment VARCHAR2(500),
    user_comment VARCHAR2(500),
    CONSTRAINT fk_booking_client FOREIGN KEY (client_id) REFERENCES Users(id),
    CONSTRAINT fk_booking_master FOREIGN KEY (master_id) REFERENCES Master_info(id)
) TABLESPACE mastergram_tablespace;

CREATE TABLE masters_followers (
    client_id NUMBER,
    master_id NUMBER,
    CONSTRAINT pk_masters_followers PRIMARY KEY (client_id, master_id),
    CONSTRAINT fk_masters_followers_client FOREIGN KEY (client_id) REFERENCES Users(id),
    CONSTRAINT fk_masters_followers_master FOREIGN KEY (master_id) REFERENCES Users(id)
) TABLESPACE mastergram_tablespace;

DROP TABLE masters_followers;
DROP TABLE Booking;
DROP TABLE Post;
DROP TABLE Users;
DROP TABLE Credential;
DROP TABLE Master_info;











